### PR TITLE
adds a debug option

### PR DESCRIPTION
**Pull request by cambridgemike**
Not sure if this is how you would want to implement such a feature, but I found this helpful. It might be helpful to output a statement to the logger in the case of debug being true.

### CODE REVIEW

**Comment by seuros** [comment]
@cambridgemike , can you test master ? 
you should require hosted_graphite/testing in your test helper.

I'm :+1:  fr the IP performance, but i have to ask Dave if they are not using a load balancer first.

**Comment by cambridgemike** [comment]
Ah, whoops, hardcoding the IP was a stopgap for myself, didn't mean to push it into this branch.

**Comment by derpston** [comment]
As a member of the Hosted Graphite team, it's cool that you're all working on this. Thanks. :)

As for the static IP thing, we generally discourage people from doing that because we do need to change DNS entries occasionally. To avoid the performance hit of making a DNS request before sending each UDP packet, we recommend making a socket object look it up once, then cache it for a while, as shown in this gist: https://gist.github.com/derpston/87d1ba13413c741655f4 (I realise this is Python, but Ruby should be similar)

Once that is done, the only tricky bit is to make sure to throw that socket object away every 1 minute or 5 minutes or something reasonable. It's not obeying DNS TTLs, but it's close enough and should solve the performance concern by amortising the lookup cost over several minutes.

This is the approach we took with https://github.com/derpston/python-graphiteudp (which uses https://github.com/derpston/python-socketcache, which implements the behaviour described above) and it has worked well for us.

**Comment by seuros** [comment]
Thank you @derpston

**Pull request closed without merging**
